### PR TITLE
use dedicate multistage dockerfile to avoid break Jenkins

### PR DESCRIPTION
**Pull request by shokakucarrier**

### CODE REVIEW

**Comment by shokakucarrier** [comment]
If we want to keep both Jenkins and pipeline functional we have to use two different Dockerfile

**Comment by ruhan1** [comment]
I like the idea of 'addition instead of modification' which means adding new module or code to replace old things while old things work until it is fully dumped. I guess those new docker files are for the pipeline ci, so I am Ok to adding them. 

Meanwhile, we should compare carefully between different ways to do ci. If the new way is better than old, we adopt it. If it is equally good, or not as good as old way, we'd better not introduce more complexity to our life. It is beyond my knowledge to judge the pipeline ci and Jenkins ci, so I'd like to leave the answer to others. IMO, eventually we should only keep one set of docker files unless there are special request to use both.

**Comment by shokakucarrier** [comment]
I'd like to do a if statement for dockerfile but that is such a hack and won't be better than this.
In our case we use Jenkins to do CI verification and pipeline to do release and build, if we want to keep only one stuff I suggest we move to Git actions to do CI verification and pipeline as it is, then we can get rid off jenkins completely.
But before that day comes, we need both.

**Review by ligangty — COMMENTED** [review]
LGTM

**Pull request merged**
